[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = [
    ".",
]
include = [
    "knockdaemon2*",
]
exclude = [
    "knockdaemon2_test*",
]

[tool.setuptools.package-data]
mypkg = [
    "*.txt",
    "*.md",
    "*.py",
]

[project]
name = "knockdaemon2"
description = "knockdaemon2"
version = "3.13.0"
# Official support for 3.11 and 3.13+ only...
requires-python = ">= 3.7"
dynamic = ["dependencies", "optional-dependencies"]
readme = "README.md"
license = "GPL-3.0"
license-files = ["LICENSE.md"]
keywords = ["python", "gevent"]
authors = [
    { name = "Laurent Labatut", email = "laurent@labatut.net" },
    { name = "Laurent Champagnac", email = "champagnac.laurent@gmail.com" },
]
maintainers = [
    { name = "Laurent Labatut", email = "laurent@labatut.net" },
    { name = "Laurent Champagnac", email = "champagnac.laurent@gmail.com" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Other Environment",
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries",
    "Natural Language :: English",
]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
optional-dependencies.test = { file = ["requirements_test.txt"] }

[project.entry-points."knockdaemon2"]
"knockdaemon2" = "knockdaemon2.Daemon.KnockDaemon:run"

[project.urls]
Homepage = "https://github.com/champax/knockdaemon2"
Repository = "https://github.com/champax/knockdaemon2"
