#!/bin/sh
### BEGIN INIT INFO
# Provides:          <NAME>
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       knockdaemon2
### END INIT INFO

RUNAS=root
NAME=knockdaemon2
PIDFILE=/var/run/${NAME}.pid
LOGFILE=/var/log/${NAME}
CONFIGFILE=/etc/knock/knockdaemon2/knockdaemon2.ini
DAEMON_OPTS="-pidfile=$PIDFILE -stderr=$LOGFILE.err -stdout=/dev/null -logfile=$LOGFILE.log -loglevel=INFO -maxopenfiles=4096 -user=$RUNAS -c=${CONFIGFILE}"
SCRIPT="/opt/knock/.env/knockdaemon2/bin/knockdaemon2 $DAEMON_OPTS"

start() {

  echo 'Starting service…' >&2
  ${SCRIPT} start
  echo 'Service started' >&2
}

stop() {
  echo 'Stopping service…' >&2
  ${SCRIPT} stop
  echo 'Service stopped' >&2
}

status() {
        printf "%-50s" "Checking $NAME..."
        echo
        ${SCRIPT} status
        exit $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart}"
esac
